services:
  server:
    env_file: .env
    image: 288761769929.dkr.ecr.us-east-1.amazonaws.com/meddiflux:latest
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp